# Default application configuration that all configurations inherit from.

scss_files: "app/assets/stylesheets/**/*.scss"

linters:
  BorderZero:
    enabled: false

  Indentation:
    exclude:
      - 'path/to/file.scss'
      - 'path/to/directory/**'
    severity: warning
    width: 2
